name: project with ci/cd flow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java and Maven
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: run tests
        run: mvn clean test
#      - name: Build & push docker image
#        uses: mr-smithers-excellent/docker-build-push@v5
#        with:
#          image: vovafrolov11/ci-cd-example
#          tags: latest
#          registry: docker.io
#          dockerfile: Dockerfile.ci
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
